const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const {chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const root=path.resolve(process.argv[2]),browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
  const context=await browser.newContext({offline:true,acceptDownloads:true,viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(root,'index.html')).href);
  await page.waitForFunction(()=>window.REVIEW_APP?.snapshot().visible>0);
  assert.match(await page.locator('#coverage').textContent(),/3019份 \/ 259图/);
  assert.equal(parseInt(await page.locator('#list-count').textContent(),10),await page.evaluate(()=>REVIEW_DATA.manifest.screening.candidate_count));
  await page.locator('#category').selectOption('cue:singleton');
  assert.ok(await page.locator('#rows').textContent().then(t=>t.includes('单人簇')));
  await page.locator('#category').selectOption('suspect');
  const fullChart=await page.locator('#chart-count').textContent();
  assert.ok(parseInt(fullChart,10)>21);
  await page.locator('#mode').selectOption('linear');
  assert.equal(parseInt(await page.locator('#list-count').textContent(),10),await page.evaluate(()=>REVIEW_DATA.manifest.screening.candidate_count));
  await page.locator('#mode').selectOption('curve');
  await page.locator('#category').selectOption('all');
  assert.equal(await page.locator('#list-count').textContent(),'3019份');
  assert.equal(await page.locator('#chart-count').textContent(),fullChart);
  await page.locator('#reset').click();
  assert.equal(parseInt(await page.locator('#list-count').textContent(),10),await page.evaluate(()=>REVIEW_DATA.manifest.screening.candidate_count));
  const id=await page.evaluate(()=>REVIEW_DATA.rows.find(r=>!r.known_wrong&&r.modes.curve.rank!==null).id);
  await page.locator('#search').fill(id);
  const point=await page.evaluate(id=>{const r=REVIEW_DATA.rows.find(v=>v.id===id),q=r.modes.curve.quality.gt_revised,c=document.querySelector('#scatter'),b=c.getBoundingClientRect();
    return {x:(52+q.iou*(1000-74))*b.width/1000,y:(320-35-Math.log1p(Math.min(100,Math.abs(q.dy_px)))/Math.log(101)*(320-35-18))*b.height/320};},id);
  await page.locator('#scatter').click({position:point});
  assert.equal((await page.evaluate(()=>REVIEW_APP.snapshot())).selected,id);
  await page.waitForFunction(id=>REVIEW_APP.snapshot().selected===id&&REVIEW_APP.snapshot().imageReady,id);
  await page.locator('#panorama').evaluate(e=>{if(!e.width||!e.height)throw Error('empty canvas')});
  assert.match(await page.locator('#prior').textContent(),/已有审查与同图资料/);
  await page.locator('#zoom').fill('2');assert.equal(await page.locator('#panorama').evaluate(e=>e.style.width),'2048px');
  assert.equal(await page.locator('#points').inputValue(),'raw');
  await page.locator('#points').selectOption('effective');
  const peerId=await page.evaluate(id=>{const image=REVIEW_DATA.rows.find(r=>r.id===id).image_id;return REVIEW_DATA.rows.find(r=>r.image_id===image&&r.id!==id)?.id;},id);
  assert.ok(peerId);
  await page.evaluate(id=>REVIEW_APP.select(id),peerId);
  assert.equal(await page.locator('#points').inputValue(),'raw');
  await page.evaluate(id=>REVIEW_APP.select(id),id);
  await page.locator('#reference').selectOption('hohonet');
  await page.locator('#reference').selectOption('peer');await page.locator('#peer').selectOption({index:1});
  await page.locator('#mode').selectOption('linear');await page.locator('#gt').selectOption('gt_original');
  await page.locator('#category').selectOption('failure');assert.ok((await page.locator('#list-count').textContent()).includes('份'));
  const failure=await page.evaluate(()=>REVIEW_DATA.rows.find(r=>r.modes.linear.failure).id);
  await page.evaluate(id=>REVIEW_APP.select(id),failure);
  await page.waitForFunction(()=>!document.getElementById('case-content').hidden);
  assert.equal((await page.evaluate(()=>REVIEW_APP.snapshot())).selected,failure);
  assert.match(await page.locator('#case-state').textContent(),/不可评价/);
  await page.locator('#verdict').selectOption('representation');await page.locator('#comment').fill('浏览器验收临时裁决');
  assert.equal((await page.evaluate(()=>REVIEW_APP.snapshot())).decisions,1);
  const download=page.waitForEvent('download');await page.locator('#export').click();const saved=JSON.parse(fs.readFileSync(await (await download).path(),'utf8'));
  assert.equal(saved.decisions[failure].verdict,'representation');assert.equal(saved.contract_version,'consensus_research_20260923_v1');
  await page.reload();await page.waitForFunction(()=>window.REVIEW_APP?.snapshot().visible>0);
  await page.evaluate(id=>REVIEW_APP.select(id),failure);await page.waitForFunction(()=>!document.getElementById('case-content').hidden);
  assert.equal(await page.locator('#verdict').inputValue(),'representation');
  await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>window.REVIEW_APP?.snapshot().visible>0);
  await page.locator('#import').setInputFiles({name:'review.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await page.waitForFunction(()=>document.querySelector('#decision-message').textContent.includes('导入成功'));
  assert.equal((await page.evaluate(()=>REVIEW_APP.snapshot())).decisions,1);
  await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,contract_version:'wrong'}))});
  await page.waitForFunction(()=>document.querySelector('#decision-message').textContent.includes('导入失败'));
  await page.locator('#category').selectOption('known');assert.equal(await page.locator('#list-count').textContent(),'2份');
  assert.deepEqual(errors,[]);
  console.log('PASS: offline full index, real image/canvas, layers, zoom, mode, failure/known queues, save/reload/export/import');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
