const {chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader']});try{const p=await b.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('analysis_results/order_studio_20260926/index.html')).href);await p.waitForFunction(()=>STUDIO.snapshot().imageReady);
assert.equal(await p.evaluate(()=>dataset.cases.flatMap(c=>c.variants).length),90);
await p.locator('#points-only').click();const text=await p.evaluate(()=>{const ctx=$('panorama').getContext('2d'),old=ctx.fillText,labels=[];ctx.fillText=function(t,...a){labels.push(t);old.call(this,t,...a)};try{drawPanorama();return labels;}finally{ctx.fillText=old;}});assert.deepEqual(text,[]);await p.locator('#points-only').click();
const legacy=await p.evaluate(()=>{const s=activeSource();return {schema:'order_review_20260928_v2',examples_only:true,records:{[sourceId(s)]:{binding:JSON.stringify({id:sourceId(s),points:s.before_preprocessing_points,labels:s.effective_point_labels,links:s.links_zero_based}),status:'draft',order:s.links_zero_based.map((_,i)=>i),cause:'',updated_at:'2026-09-28T00:00:00Z'}}};});await p.locator('#import-orders').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await p.waitForFunction(()=>document.getElementById('save-state').textContent.includes('导入'));assert.match(await p.locator('#save-state').textContent(),/导入完成/);assert.equal(await p.evaluate(()=>saved[sourceId(activeSource())].status),'draft');
await p.locator('#pairing-note').fill('测试匹配错误');await p.locator('#pairing-problem').click();assert.match(await p.locator('#save-state').textContent(),/匹配错误/);await p.reload();await p.waitForFunction(()=>STUDIO.snapshot().imageReady);assert.equal(await p.locator('#pairing-note').inputValue(),'测试匹配错误');assert.match(await p.locator('#save-state').textContent(),/匹配错误/);
await p.evaluate(()=>{let i=dataset.cases.findIndex(c=>c.variants.some(v=>v.source.object_kind!=='annotation'));chooseCase(i);});await p.waitForFunction(()=>STUDIO.snapshot().imageReady);await p.evaluate(()=>{const i=dataset.cases[currentCase].variants.findIndex(v=>v.source.object_kind!=='annotation');$('variant-select').value=i;chooseVariant(i);});await p.locator('#confirm-order').click();assert.match(await p.locator('#save-state').textContent(),/已确认/);assert.ok(await p.evaluate(()=>saved[sourceId(activeSource())]?.status==='confirmed'));
await p.locator('#next-order').click();assert.ok(await p.locator('#object-progress').textContent());assert.ok(await p.locator('#confirm-order').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await p.screenshot({path:'analysis_results/order_studio_20260926/qa-candidates.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS 90 objects, GT saving, pairing status, points-only, first-screen controls');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
