const {chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const url=pathToFileURL(path.resolve('analysis_results/pairing_completion_review_20260929/index.html')).href;
 const ready=()=>page.waitForFunction(()=>image.complete&&image.naturalWidth>0);
 await page.goto(url);await ready();assert.equal(await page.locator('#case option').count(),15);
 assert.equal(await page.evaluate(()=>Object.keys(records).length),0);
 assert.equal(await page.evaluate(()=>pairs.flat().length+deleted().length),await page.evaluate(()=>row().points.length));
 const first=await page.evaluate(()=>row().object_id);
 await page.locator('#confirm').click();assert.equal(await page.evaluate(()=>records[row().object_id].status),'checked');
 assert.equal(await page.evaluate(()=>row().object_id),first);assert.ok(await page.evaluate(()=>image.naturalWidth>0));
 await page.locator('#pair-list button').first().click();await page.locator('#confirm').click();assert.match(await page.locator('#status').innerText(),/未配对/);
 assert.equal(await page.evaluate(()=>records[row().object_id].status),'draft');
 await page.locator('#clear').click();await page.locator('#confirm').click();
 await page.locator('#mode').selectOption('all');
 const b6=await page.evaluate(()=>data.cases.findIndex(r=>r.proposals.length===2));await page.locator('#case').selectOption(String(b6));await ready();
 await page.locator('#confirm').click();assert.match(await page.locator('#status').innerText(),/选择修点/);
 await page.locator('#proposal').selectOption('delete_3');assert.deepEqual(await page.evaluate(()=>deleted()),[2]);
 assert.ok(await page.locator('#point-buttons button').nth(2).isDisabled());await page.locator('#confirm').click();
 await page.locator('#proposal').selectOption('delete_1');assert.equal(await page.evaluate(()=>records[row().object_id].status),'draft');
 assert.deepEqual(await page.evaluate(()=>deleted()),[0]);await page.locator('#confirm').click();
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);
 const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.order_confirmed,false);assert.equal(Object.keys(exported.records).length,2);
 await page.reload();await ready();await page.locator('#mode').selectOption('all');await page.locator('#case').selectOption(String(b6));await ready();
 assert.deepEqual(await page.evaluate(()=>deleted()),[0]);assert.equal(await page.evaluate(()=>records[row().object_id].status),'checked');
 const target=await page.evaluate(()=>data.cases.findIndex(r=>r.image_code==='uNb9QFRL6hY-36'));await page.locator('#case').selectOption(String(target));await ready();
 assert.equal(await page.evaluate(()=>pairs.length),4);
 if(process.env.PAIRING_QA)await page.screenshot({path:process.env.PAIRING_QA,fullPage:true});
 const page2=await browser.newPage();await page2.goto(url);await page2.locator('#import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page2.waitForFunction(()=>$('status').textContent==='导入完成。');
 assert.equal(await page2.evaluate(()=>Object.keys(records).length),2);
 const invalid=structuredClone(exported);Object.values(invalid.records)[0].deleted_source_indices=[999];await page2.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page2.waitForFunction(()=>$('status').textContent.startsWith('导入未应用'));
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('test full');};});await page.locator('#clear').click();await page.locator('#next').click();assert.equal(await page.evaluate(()=>current),target);assert.match(await page.locator('#status').innerText(),/未保存/);
 assert.deepEqual(errors,[]);console.log('PASS 15份完整配对：留图、修改、完整覆盖、删点选择、P号、刷新、导入导出、保存失败保护');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
