const {chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.resolve('analysis_results/pairing_review_20260929/index.html')).href;
 const ready=()=>page.waitForFunction(()=>image.complete&&image.naturalWidth>0);
 await page.goto(url);await ready();assert.equal(await page.locator('#case option').count(),34);
 const even=await page.evaluate(()=>data.cases.findIndex(r=>r.points.length%2===0));await page.locator('#case').selectOption(String(even));await ready();
 const first=await page.evaluate(()=>row().object_id);
 assert.equal(await page.evaluate(()=>pairs.length),0);
 await page.locator('#confirm').click();assert.equal(await page.evaluate(()=>records[row().object_id].status),'checked');
 assert.equal(await page.evaluate(()=>records[row().object_id].pairs.length),0);
 await page.evaluate(()=>{const sorted=row().points.map((p,i)=>i).sort((a,b)=>row().points[a][1]-row().points[b][1]);pick(sorted[0]);});
 await page.locator('#confirm').click();assert.match(await page.locator('#status').innerText(),/还有一个已选点/);
 await page.evaluate(()=>{const sorted=row().points.map((p,i)=>i).sort((a,b)=>row().points[a][1]-row().points[b][1]);pick(sorted[sorted.length-1]);});
 await page.locator('#confirm').click();assert.equal(await page.evaluate(()=>row().object_id),first);
 assert.equal(await page.evaluate(()=>records[row().object_id].status),'checked');assert.equal(await page.evaluate(()=>records[row().object_id].order_confirmed),false);
 assert.equal(await page.evaluate(()=>records[row().object_id].pairs.length),1);
 assert.equal(await page.evaluate(()=>records[row().object_id].review_mode),'corrections_only');
 assert.equal(await page.evaluate(()=>records[row().object_id].untouched_points),'accepted_without_correction');
 const order=await page.evaluate(()=>JSON.stringify(records[row().object_id].pairs));
 await page.reload();await ready();await page.locator('#mode').selectOption('all');await page.locator('#case').selectOption(String(even));await ready();
 assert.equal(await page.evaluate(()=>JSON.stringify(records[row().object_id].pairs)),order);
 assert.ok(await page.evaluate(()=>{try{validatePairs(row(),[[0,1],[0,2]]);return false;}catch{return true;}}));
 const odd=await page.evaluate(()=>data.cases.findIndex(r=>r.points.length%2));await page.locator('#case').selectOption(String(odd));await ready();
 await page.locator('#confirm').click();assert.equal(await page.evaluate(()=>records[row().object_id].status),'checked');
 await page.locator('#note').fill('奇数点，待核查缺点或多点');await page.locator('#defer').click();assert.equal(await page.evaluate(()=>records[row().object_id].status),'deferred');
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);
 const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.scope,'pairing_only');assert.equal(exported.order_confirmed,false);assert.equal(Object.keys(exported.records).length,2);
 const corrupt=structuredClone(exported);Object.values(corrupt.records)[0].binding='bad';await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(corrupt))});await page.waitForFunction(()=>$('status').textContent.startsWith('导入未应用'));
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('test full');};});const idx=await page.evaluate(()=>current);
 await page.locator('#clear').click();await page.locator('#next').click();assert.equal(await page.evaluate(()=>current),idx);assert.match(await page.locator('#status').innerText(),/未保存/);
 await page.reload();await ready();await page.locator('#mode').selectOption('all');await page.locator('#case').selectOption('0');await ready();
 if(process.env.PAIRING_QA)await page.screenshot({path:process.env.PAIRING_QA,fullPage:true});
 const page2=await browser.newPage();await page2.goto(url);await page2.waitForFunction(()=>image.complete&&image.naturalWidth>0);await page2.locator('#import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page2.waitForFunction(()=>$('status').textContent==='导入完成。');assert.equal(await page2.evaluate(()=>Object.keys(records).length),2);
 assert.deepEqual(errors,[]);console.log('PASS 局部配对：空修正/单对/奇数可完成/选点保护/确认留图/刷新/导入导出/存储失败');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
