const {chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const ROOT='D:/Work/HOHONET',URL='http://127.0.0.1:8769/';
(async()=>{
 const browser=await chromium.launch({headless:true}),contexts=[],errors=[];
 const evidence={browser:'用户电脑上的隔离 Chromium（Playwright）',user_browser_profile_used:false};
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});contexts.push(context);
  const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(URL);
  const ready=async(page=p,id)=>{await page.waitForFunction(id=>window.POINT_REVIEW_STATE?.().imageReady&&(!id||POINT_REVIEW_STATE().current===id),id);};
  const state=()=>p.evaluate(()=>POINT_REVIEW_STATE());await ready();await p.locator('#scope-filter').selectOption('all');
  assert(await p.locator('#quick-editor').isVisible());assert.equal(await p.locator('#case-select option').count(),109);
  const cases=await p.evaluate(()=>POINT_REVIEW_DATA.cases.map((c,i)=>({i,id:c.record_id})));
  const goto=async id=>{await p.locator('#case-select').selectOption(String(cases.find(c=>c.id===id).i));await ready(p,id);};
  const clickXY=async(x,y)=>{await p.locator('#panorama').scrollIntoViewIfNeeded();const b=await p.locator('#panorama').boundingBox();await p.locator('#panorama').click({position:{x:b.width*x/1024,y:b.height*y/512}});};
  await goto('R00003');const raw=(await state()).points;
  await p.locator('#tool-add').click();assert.equal((await state()).version,'draft');assert.equal((await state()).records.R00003.base_version,'raw');
  assert.match(await p.locator('#mode-guide').innerText(),/单击一次/);
  await clickXY(850,130);let d=(await state()).records.R00003;
  assert.equal(d.points.length,raw.length+1);assert(d.points.at(-1).id.startsWith('new:'));assert.equal(await p.locator('#panorama').getAttribute('data-tool'),'select');
  assert.match(await p.locator('#save-indicator').innerText(),/已自动保存/);
  await clickXY(870,150);assert.equal((await state()).records.R00003.points.length,raw.length+1);
  await p.locator('#undo-step').click();d=(await state()).records.R00003;assert.deepEqual(d.points,raw);assert.equal(d.operations.at(-1).type,'undo');
  await p.locator('#tool-add').click();await clickXY(850,130);d=(await state()).records.R00003;const added=d.points.at(-1).id;
  await p.locator('#tool-add').click();await p.locator('#cancel-selection').click();assert.equal(await p.locator('#panorama').getAttribute('data-tool'),'select');assert.deepEqual((await state()).records.R00003,d);
  await p.locator('#tool-move').click();await p.locator('#panorama').scrollIntoViewIfNeeded();let b=await p.locator('#panorama').boundingBox();let s=await state();const p1=s.points.find(v=>v.label==='p1');
  await p.mouse.move(b.x+b.width*p1.x/1024,b.y+b.height*p1.y/512);await p.mouse.down();await p.mouse.move(b.x+b.width*(p1.x+15)/1024,b.y+b.height*(p1.y+5)/512,{steps:4});await p.mouse.up();
  d=(await state()).records.R00003;assert(Math.abs(d.points[0].x-p1.x-15)<1);assert.equal(d.operations.at(-1).type,'move');
  await p.locator('#tool-delete').click();const p3=(await state()).points.find(v=>v.label==='p3');await clickXY(p3.x,p3.y);assert(await p.locator('#quick-delete').isEnabled());
  await p.locator('#quick-delete').click();assert.equal((await state()).records.R00003.points[2].deleted,true);
  await p.locator('#undo-step').click();assert.equal((await state()).records.R00003.points[2].deleted,undefined);assert.equal((await state()).records.R00003.points[3].label,'p4');
  await p.locator('#tool-pair').click();await p.locator('#edit-point-buttons button').filter({hasText:/^p1$/}).click();assert.match(await p.locator('#mode-guide').innerText(),/再单击对应下点/);
  await p.locator('#cancel-selection').click();assert.deepEqual((await state()).records.R00003.pairs,[]);
  await p.locator('#tool-pair').click();await p.locator('#edit-point-buttons button').filter({hasText:/^p1$/}).click();await p.locator('#edit-point-buttons button').filter({hasText:/^p2$/}).click();
  assert.equal((await state()).records.R00003.pairs.length,1);
  const saved=(await state()).records.R00003;const cacheKey=(await state()).key;
  await p.locator('#variant-select').selectOption('0');await p.locator('#tool-move').click();assert.deepEqual((await state()).records.R00003,saved);assert.equal((await state()).version,'draft');
  await goto('R00541');assert.equal(await p.locator('#panorama').getAttribute('data-tool'),'select');
  await p.locator('#tool-add').click();assert(await p.locator('#baseline-choice').isVisible());assert.equal((await state()).records.R00541,undefined);
  assert.match(await p.locator('#baseline-explanation').innerText(),/p5/);
  await p.locator('#baseline-options button').filter({hasText:/历史生效/}).click();assert.equal((await state()).records.R00541.base_version,'historical');assert(!(await state()).points.some(v=>v.label==='p5'));
  await clickXY(850,130);await p.locator('#undo-step').click();assert(!(await state()).points.some(v=>v.label==='p5'));
  await p.reload();await ready(p,'R00541');assert.equal((await state()).version,'draft');assert(!(await state()).points.some(v=>v.label==='p5'));
  await goto('R00003');assert.deepEqual((await state()).records.R00003,saved);assert((await state()).points.some(v=>v.id===added));
  const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#export-patches').click()]);const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.apply_to_formal,false);assert(exported.records.R00003.operations.some(o=>o.type==='undo'&&o.undo_of));
  assert.equal(cacheKey,exported.schema+':'+exported.source_hash+':'+exported.queue_hash);
  const ctx2=await browser.newContext();contexts.push(ctx2);const p2=await ctx2.newPage();p2.on('pageerror',e=>errors.push(e.message));await p2.goto(URL);await ready(p2);await p2.locator('#scope-filter').selectOption('all');
  await p2.locator('#import-patches').setInputFiles({name:'ux-test-return.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await p2.waitForFunction(()=>document.getElementById('edit-status').textContent==='导入完成。');assert.deepEqual(await p2.evaluate(()=>POINT_REVIEW_STATE().records),exported.records);
  await p2.locator('#case-select').selectOption(String(cases.find(c=>c.id==='R00541').i));await ready(p2,'R00541');await p2.reload();await ready(p2,'R00541');assert.deepEqual(await p2.evaluate(()=>POINT_REVIEW_STATE().records),exported.records);
  // 旧格式草稿使用相同缓存键，无undo操作；升级不覆盖它。
  const legacy=await p.evaluate(()=>{const s=POINT_REVIEW_DATA.cases.find(c=>c.record_id==='R00003');return PointReview.add(PointReview.create(s,'raw'),810,180,'new:existing-old-draft');});
  const ctx3=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});contexts.push(ctx3);
  await ctx3.addInitScript(({key,d})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({R00003:d}));},{key:cacheKey,d:legacy});
  const p4=await ctx3.newPage();p4.on('pageerror',e=>errors.push(e.message));await p4.goto(URL);await ready(p4);await p4.locator('#scope-filter').selectOption('all');await p4.locator('#case-select').selectOption(String(cases.find(c=>c.id==='R00003').i));await ready(p4,'R00003');assert.deepEqual(await p4.evaluate(()=>POINT_REVIEW_STATE().records.R00003),legacy);
  await p4.locator('#tool-move').click();assert.deepEqual(await p4.evaluate(()=>POINT_REVIEW_STATE().records.R00003),legacy);
  // 保存失败只在隔离测试上下文模拟；内存编辑可导出，切换被阻止。
  await p4.evaluate(key=>{const originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('测试：存储空间不足');return originalSet.call(this,k,v);};},cacheKey);
  await p4.locator('#tool-add').click();await p4.locator('#panorama').scrollIntoViewIfNeeded();b=await p4.locator('#panorama').boundingBox();await p4.locator('#panorama').click({position:{x:b.width*890/1024,y:b.height*190/512}});
  assert.match(await p4.locator('#save-indicator').innerText(),/尚未保存/);assert.equal((await p4.evaluate(()=>POINT_REVIEW_STATE().records.R00003)).points.length,legacy.points.length+1);
  await p4.locator('#case-select').selectOption(String(cases.find(c=>c.id==='R00541').i));assert.equal(await p4.evaluate(()=>POINT_REVIEW_STATE().current),'R00003');
  const [memoryDownload]=await Promise.all([p4.waitForEvent('download'),p4.locator('#export-patches').click()]);const memoryExport=JSON.parse(fs.readFileSync(await memoryDownload.path(),'utf8'));assert.equal(memoryExport.records.R00003.points.length,legacy.points.length+1);
  assert.deepEqual(errors,[]);evidence.passed=true;evidence.page_errors=errors;
  evidence.auto_draft_and_single_click_add=true;evidence.add_exits_mode_prevents_double_add=true;evidence.undo_delete_drag_pair_cancel_passed=true;
  evidence.history_choice_and_no_deleted_point_restore=true;evidence.existing_old_draft_unchanged=true;evidence.switch_reload_resume_export_import=true;
  evidence.storage_failure_preserves_memory_and_blocks_switch=true;evidence.cache_key_unchanged=true;
  console.log('PASS UX: auto draft / one-shot add / undo / delete / drag / pair / cancel / history choice / existing drafts / switch & refresh / export & import / storage failure');
 }finally{for(const c of contexts)await c.close();await browser.close();evidence.test_contexts_closed=true;evidence.test_drafts_persisted_to_user_profile=false;fs.writeFileSync(ROOT+'/analysis_results/point_edit_review_20261009/ux_browser_verification.json',JSON.stringify(evidence,null,2));}
})().catch(e=>{console.error(e);process.exitCode=1;});
