/* Real release acceptance: offline file URL, no server, no synthetic points. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=path.resolve(process.argv[2]),shots=path.resolve(process.argv[3]);fs.mkdirSync(shots,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const ctx=await browser.newContext({offline:true,viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[],remote=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
 const mod=key=>page.locator(`[data-module="${key}"]`).click();
 const text=async(sel,needle)=>assert.ok((await page.locator(sel).innerText()).includes(needle),needle);
 try{
  await page.goto(pathToFileURL(path.join(dir,'index.html')).href);
  await page.waitForSelector('.js-plotly-plot');
  assert.equal(await page.locator('#navigation button').count(),6);
  assert.equal(await page.locator('.metric-value').first().innerText(),'3019份');
  assert.equal(await page.locator('#definition-cards').isVisible(),false);
  await text('#results','DINOv3');await text('#results','Bi-Layout_历史清单ok');
  await page.screenshot({path:path.join(shots,'01-overview.png'),fullPage:false});
  await mod('annotation');await page.getByRole('button',{name:'查看 Manual/OOS · 无辅助计算 · 完整链接 · 25.6px',exact:true}).click();
  await page.waitForSelector('.js-plotly-plot');
  assert.deepEqual(await page.locator('.metric-value').allInnerTexts(),['110图','1940份','515份','27图']);
  const traceCounts=await page.locator('.js-plotly-plot').evaluateAll(ps=>ps.map(p=>p.data.length));assert.deepEqual(traceCounts,[1,1]);
  await page.locator('#compare').check();
  const candidateId=await page.evaluate(()=>RESEARCH_DATA.views.find(v=>v.method==='affinity'&&!v.building).id);
  await page.locator('#compare-view').selectOption(candidateId);await text('#results','537');await text('#results','23');
  await page.locator('#compare').uncheck();
  await page.screenshot({path:path.join(shots,'02-annotation.png'),fullPage:false});
  const caseId=await page.evaluate(()=>RESEARCH_DATA.cases[0].image_id);
  await page.locator('#image-search').fill(caseId);await page.locator('.image-card').click();
  await page.waitForSelector('.panorama-scroll circle');
  assert.equal(await page.locator('[aria-label="人员点集"] option').count(),15);
  await text('#drawer','全部簇成员与完整点集 · 15 份');
  assert.ok(await page.locator('.panorama-scroll circle').count()>=8);
  await page.locator('[aria-label="对照点集"]').selectOption({index:2});
  await page.locator('#drawer').evaluate(e=>e.scrollTop=0);
  await page.screenshot({path:path.join(shots,'03-full-case.png'),fullPage:false});
  const ready=page.waitForEvent('framenavigated',{predicate:f=>f.url().includes('/cases/')});
  await page.getByRole('button',{name:'展开此点集的 3D 预览'}).click();const frame=await ready;
  await frame.waitForFunction(()=>window.STUDIO?.snapshot().textureReady);
  assert.equal(await frame.evaluate(()=>STUDIO.snapshot().imageReady),true);
  await page.keyboard.press('Escape');
  await page.locator('#filter-building').selectOption('uNb9QFRL6hY');
  const imageScope=await page.evaluate(id=>RESEARCH_DATA.views.find(v=>v.method==='complete'&&v.image===id),caseId);
  await page.locator('#filter-room').selectOption(imageScope.room);await page.locator('#filter-image').selectOption(caseId);
  await mod('stability');await text('#results','不是多轮修订质量上限');await text('#results','预定编号1—3');
  const curve=await page.locator('.js-plotly-plot').nth(1).evaluate(p=>({x:p.data[0].x,y:p.data[0].y,m:p.data[0].customdata}));
  assert.equal(curve.x[0],4);assert.equal(curve.m[0][4].split('、').length,4);assert.ok(curve.x.length>3);
  await page.screenshot({path:path.join(shots,'04-replay.png'),fullPage:false});
  await mod('people');const slider=page.locator('[aria-label="进入顺序重放步骤"]');await slider.fill('4');
  await page.locator('#filter-method').selectOption('affinity');await mod('stability');await text('#results','未计算');
  await page.locator('#reset').click();await page.locator('#filter-condition').selectOption('Manual/OOS · 无辅助计算');await page.locator('#filter-method').selectOption('affinity');await mod('rooms');
  const mae=await page.locator('.js-plotly-plot').first().evaluate(p=>p.data[0].y[0]);assert.ok(Math.abs(mae-7.593512767425806)<1e-9);
  await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:path.join(shots,'05-rooms-projection.png'),fullPage:false});
  await page.locator('#reset').click();await page.locator('#filter-condition').selectOption('semi · 描述覆盖');await mod('annotation');await text('#results','530份/43图');
  await text('#results','人员／人数未匹配');assert.ok((await page.locator('#image-count').innerText()).includes('43'));
  await mod('features');await text('#results','DINOv3');await text('#results','未接入当前版本');
  await page.setViewportSize({width:1366,height:768});await page.screenshot({path:path.join(shots,'06-features-laptop.png'),fullPage:false});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(remote,[]);assert.deepEqual(errors,[]);
  console.log('PASS real release: census/coverage, scope and method comparisons, 15 full case pointsets, shared offline WebGL, finite-pool replay members, candidate unavailable, room MAE, Semi isolation, feature coverage; no remote requests/page errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
