const assert=require('node:assert/strict');
const {validateReviewReconciliation:base}=require('../tools/thesis_main/analysis/review_reconciliation_panel_20260925.js');
const {validateReturn,returnResolved,usageText}=require('../tools/thesis_main/analysis/review_return_20260927.js');
const date='2026-09-27T00:00:00Z',binding={id:'return'},legacy={id:'old'};
const c={image_id:'i',review:{annotation_ids:['a']},return_review:{issues:[{id:'q'}]}};
const data={binding,return_review:{legacy_binding:legacy},cases:[c]},is=new Set(['i']),as=new Set(['a']);
const old={schema:'review_reconciliation_decisions_v1',binding:legacy,image_decisions:{i:{status:'resolved',category:'ordinary',comment:'原话',updated_at:date}},annotation_decisions:{}};
let converted=validateReturn(old,data,is,as,base);
assert.equal(converted.image_decisions.i.comment,'原话');assert.equal(returnResolved(c,converted),false,'图级确认不能隐藏问题');
const value={schema:'review_return_decisions_v2',binding,...converted};
value.issue_decisions.q={status:'resolved',comment:'已对照原图',updated_at:date};
assert.equal(returnResolved(c,validateReturn(value,data,is,as,base)),true);
value.traits['image:i']={status:'pending',tags:['detail','scope'],difficulty:'unrecorded',comment:'细节和范围都不同',updated_at:date};
assert.equal(returnResolved(c,validateReturn(value,data,is,as,base)),false);
assert.throws(()=>validateReturn({...value,issue_decisions:{wrong:value.issue_decisions.q}},data,is,as,base));
assert.throws(()=>validateReturn({...value,issue_decisions:{q:{status:'resolved',comment:'',updated_at:date}}},data,is,as,base));
assert.match(usageText({status:'resolved',category:'oos'},{status:'resolved',verdict:'usable'}),/不进入人员主质量/);
assert.match(usageText({status:'resolved',category:'ordinary'},{status:'resolved',verdict:'usable'}),/包含质量误差/);
assert.match(usageText({status:'resolved',category:'reference_concern'},{status:'resolved',verdict:'invalid'}),/明确排除/);
assert.deepEqual(old.image_decisions.i.comment,'原话');
const trapTrait={status:'resolved',tags:['trap_confirmed','model_unchanged'],difficulty:'unrecorded',comment:'依据历史导入设置',updated_at:date};
assert.doesNotThrow(()=>validateReturn({...value,traits:{'annotation:a':trapTrait}},data,is,as,base));
assert.throws(()=>validateReturn({...value,traits:{'annotation:a':{...trapTrait,tags:['trap_confirmed','trap_not']}}},data,is,as,base));
console.log('PASS: 独立v2/旧版导入、问题状态、保留用途、字段校验');
const {annotationDisplayState}=require('../tools/thesis_main/analysis/review_return_20260927.js');
const marked={...c,return_review:{issues:[{id:'q',annotation_ids:['a']}]}};
const display={annotation_decisions:{a:{status:'resolved',verdict:'invalid'}},issue_decisions:{}};
assert.equal(annotationDisplayState(marked,'a',display).state,'pending');
display.issue_decisions.q={status:'resolved'};
assert.equal(annotationDisplayState(marked,'a',display).state,'excluded');
assert.equal(annotationDisplayState(marked,'other',display).state,'context');
const referenceTrait={status:'resolved',tags:['reference_omission','scope'],difficulty:'hard',comment:'修订GT省略凹槽，同时存在范围取舍',updated_at:date};
assert.doesNotThrow(()=>validateReturn({...value,traits:{'image:i':referenceTrait}},data,is,as,base));
assert.match(usageText({status:'resolved',category:'ordinary'},{status:'resolved',verdict:'usable'},referenceTrait),/仍纳入主分析/);
assert.match(usageText({status:'resolved',category:'ordinary'},{status:'resolved',verdict:'usable'},{...referenceTrait,tags:['reference_error','reference_omission']}),/质量指标等待核验/);
const {trapSourceText}=require('../tools/thesis_main/analysis/review_return_20260927.js');
assert.match(trapSourceText({trap_status:'confirmed_trap',trap_origin:'synthetic',model_edit_status:'unchanged_coordinates',evidence:{formal_import:'import_json/prescreen/file.json'}}),/PreScreen阶段 · 人工构造Trap；最终点集与实际初始化一致/);
assert.match(trapSourceText({trap_status:'confirmed_trap',trap_origin:'natural'}),/选用模型自然错误作为Trap/);
assert.doesNotThrow(()=>validateReturn({...value,traits:{'annotation:a':{...trapTrait,tags:['trap_synthetic']}}},data,is,as,base));
