/* Isolated browser profile: these synthetic answers never touch the user's drafts. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(process.argv[2]||'analysis_results/uncertainty_visual_review_20260907_v1');
const qa=path.join(out,'questionnaire_qa');
(async()=>{
  fs.mkdirSync(qa,{recursive:true});
  const browser=await chromium.launch({headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1080}}), errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    const url=pathToFileURL(path.join(out,'index.html')).href;
    await page.goto(url);
    assert.equal(await page.locator('input:checked').count(),0);
    assert.equal(await page.locator('#ai-advice').getAttribute('open'),null);
    await page.waitForFunction(()=>document.querySelector('#original').naturalWidth===2048);
    await page.screenshot({path:path.join(qa,'01_original.png'),fullPage:true});
    await page.locator('[name=visibility][value=partial]').check();
    await page.locator('[name=scope][value=uncertain]').check();
    await page.locator('nav [data-step="2"]').click();
    await page.waitForFunction(()=>document.querySelector('#old-panel').naturalWidth===1024);
    assert.ok(await page.locator('#old-panel').isVisible());
    await page.locator('#order-help summary').click();
    assert.match(await page.locator('#order-help').textContent(),/1,3,2,4/);
    assert.match(await page.locator('#order-help').textContent(),/问卷备份不包含预览调整/);
    await page.screenshot({path:path.join(qa,'05_order_help.png'),fullPage:true});
    await page.locator('#order-help summary').click();
    await page.locator('#variant-select').selectOption('1');
    assert.match(await page.locator('#old-panel').getAttribute('src'),/extended_panel/);
    assert.ok(fs.existsSync(path.join(out,await page.locator('#overlay-link').getAttribute('href'))));
    assert.ok(fs.existsSync(path.join(out,await page.locator('#studio-link').getAttribute('href'))));
    await page.locator('#variant-select').selectOption('5');
    assert.match(await page.locator('#order-warning').textContent(),/未核实导出排列/);
    const pointSvg=fs.readFileSync(path.join(out,await page.locator('#points-link').getAttribute('href')),'utf8');
    assert.ok(pointSvg.includes('<circle'));assert.ok(!pointSvg.includes('<path'));assert.ok(!pointSvg.includes('<line'));
    await page.locator('[name=annotation_assessment][value=all_questionable]').check();
    await page.locator('[name=human_difference][value=uncertain]').check();
    await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(qa,'02_3d.png'),fullPage:true});
    await page.locator('nav [data-step="3"]').click();
    await page.locator('#notes').fill('=测试用例，不是真人判断\n第二行,"引号"');
    await page.locator('[name=status][value=reviewed]').check();
    await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(qa,'03_answers.png'),fullPage:true});
    await page.locator('#save-next').click();
    assert.match(page.url(),/#V02$/);
    await page.locator('#previous').click();
    await page.reload();
    assert.ok(await page.locator('[name=visibility][value=partial]').isChecked());
    await page.locator('nav [data-step="3"]').click();
    assert.ok(await page.locator('[name=status][value=reviewed]').isChecked());
    const jsonDownload=page.waitForEvent('download'); await page.locator('#export-json').click();
    const backup=JSON.parse(fs.readFileSync(await (await jsonDownload).path(),'utf8'));
    assert.equal(backup.records.length,1); assert.equal(backup.records[0].ai_advice_opened,false);
    assert.equal(backup.records[0].answers.annotation_assessment,'all_questionable');
    const csvDownload=page.waitForEvent('download'); await page.locator('#export-csv').click();
    const csv=fs.readFileSync(await (await csvDownload).path(),'utf8'); assert.ok(csv.includes('"\'=测试用例')); assert.ok(csv.includes('""引号""'));
    const bad=structuredClone(backup);bad.records[0].image_id='WRONG';
    await page.locator('#import-json').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
    await page.waitForFunction(()=>document.querySelector('#error').textContent.includes('导入失败'));
    assert.equal(await page.locator('#notes').inputValue(),backup.records[0].answers.notes);
    // All 50 image identities have local HD, static 3D and interactive links.
    const data=await page.evaluate(()=>window.REVIEW_CASES);
    for(const c of data) for(const name of ['index.html','studio.css','studio.js'])
      assert.equal(fs.readFileSync(path.join(out,'cases',c.case_id,'hd/studio',name),'utf8'),fs.readFileSync(path.resolve('tools/label_studio/panorama_studio',name),'utf8'),`${c.case_id}: current Studio ${name}`);
    const rechecks=JSON.parse(fs.readFileSync(path.join(out,'visual_order_recheck_notes.json'),'utf8'));
    assert.deepEqual(Object.keys(rechecks).sort(),data.map(c=>c.case_id).sort());
    for(const c of data) assert.ok(c.ai_observation.startsWith('本次高清与点序复看（AI初步意见，可不同意）：\n'+rechecks[c.case_id]));
    assert.equal(data.length,50);assert.equal(data.filter(c=>c.has_humans).length,30);
    for(const c of data) for(const v of c.variants) for(const suffix of [v.variant+'_panel.jpg','hd/'+v.variant+'.svg','hd/'+v.variant+'_points.svg','hd/studio/index.html','hd/panorama.png']) assert.ok(fs.existsSync(path.join(out,'cases',c.case_id,suffix)));
    const candidate=data.findIndex(c=>!c.has_humans);
    await page.locator('#case-select').selectOption(String(candidate));
    await page.locator('#ai-advice summary').click();assert.ok(await page.locator('#ai-observation').isVisible());
    await page.locator('nav [data-step="2"]').click();assert.ok(await page.locator('#human-question').isHidden());assert.ok(await page.locator('#no-humans').isVisible());
    assert.ok(await page.locator('#ai-observation').isVisible());
    await page.locator('nav [data-step="3"]').click();await page.locator('[name=status][value=reviewed]').click();
    assert.ok(await page.locator('[name=status][value=draft]').isChecked());assert.ok(await page.locator('#error').isVisible());
    await page.locator('nav [data-step="1"]').click();await page.locator('[name=visibility][value=insufficient]').check();await page.locator('[name=scope][value=uncertain]').check();
    await page.locator('nav [data-step="3"]').click();await page.locator('[name=status][value=reviewed]').check();
    assert.ok(await page.locator('[name=status][value=reviewed]').isChecked());
    // OOS is a separate reviewer opinion; it never forces answers about unexamined layouts.
    await page.locator('#case-select').selectOption('1');
    await page.locator('[name=oos_assessment][value=reviewer_oos]').check();
    await page.locator('#oos-save-step').click();
    await page.locator('[name=status][value=reviewed]').click();
    assert.ok(await page.locator('[name=status][value=draft]').isChecked());
    await page.locator('nav [data-step="1"]').click();
    await page.locator('#oos-reason').fill('测试意见：左侧墙体疑似连续弧面，与当前曼哈顿规则不符；待讨论。');
    await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(qa,'06_oos.png'),fullPage:true});
    await page.locator('#oos-save-step').click();
    await page.locator('[name=status][value=reviewed]').check();
    assert.ok(await page.locator('[name=status][value=reviewed]').isChecked());
    await page.reload();
    assert.ok(await page.locator('[name=oos_assessment][value=reviewer_oos]').isChecked());
    const oosDownload=page.waitForEvent('download');await page.locator('#export-json').click();
    const oosBackup=JSON.parse(fs.readFileSync(await (await oosDownload).path(),'utf8'));
    const oosRecord=oosBackup.records.find(r=>r.case_id==='V02');
    assert.equal(oosRecord.answers.human_difference,'');assert.equal(oosRecord.answers.scope,'');
    assert.equal(oosRecord.answers.status,'reviewed');assert.match(oosRecord.answers.oos_reason,/弧面/);
    const oosCsvDownload=page.waitForEvent('download');await page.locator('#export-csv').click();
    assert.match(fs.readFileSync(await (await oosCsvDownload).path(),'utf8'),/oos_assessment/);
    await page.evaluate(()=>localStorage.clear());await page.reload();
    await page.locator('#import-json').setInputFiles({name:'oos.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(oosBackup))});
    await page.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('已导入'));
    assert.ok(await page.locator('[name=oos_assessment][value=reviewer_oos]').isChecked());
    await page.locator('[name=oos_assessment][value=in_scope]').check();
    await page.locator('nav [data-step="3"]').click();
    assert.ok(await page.locator('[name=status][value=draft]').isChecked());
    await page.locator('nav [data-step="1"]').click();
    await page.locator('[name=oos_assessment][value=suspected]').check();
    await page.locator('#oos-save-step').click();
    await page.locator('[name=status][value=reviewed]').check();
    assert.ok(await page.locator('[name=status][value=reviewed]').isChecked());
    await page.evaluate(()=>localStorage.clear());await page.reload();
    const legacy=structuredClone(backup);delete legacy.records[0].answers.annotation_assessment;delete legacy.records[0].answers.oos_assessment;delete legacy.records[0].answers.oos_reason;
    await page.locator('#import-json').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
    await page.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('已导入 1 张'));
    await page.locator('#case-select').selectOption('0'); assert.ok(await page.locator('[name=visibility][value=partial]').isChecked());
    assert.equal(await page.locator('[name=annotation_assessment]:checked').count(),0);
    assert.equal(await page.locator('[name=oos_assessment]:checked').count(),0);
    assert.equal(await page.locator('#oos-reason').inputValue(),'');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    // Corrupt stored records are not silently replaced by new answers.
    await page.evaluate(()=>localStorage.setItem('hohonet_uncertainty_review_20260907_v1','corrupt'));
    await page.reload();await page.locator('[name=visibility][value=clear]').check();
    assert.equal(await page.evaluate(()=>localStorage.getItem('hohonet_uncertainty_review_20260907_v1')),'corrupt');
    assert.match(await page.locator('#save-state').textContent(),/不可用/);
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(qa,'RESULT.json'),JSON.stringify({passed:true,synthetic_answers_only:true,checks:['blank_initial_answers','HD_2048','visible_static_3D','all_50_case_assets','local_autosave_reload','JSON_roundtrip','CSV_escaping','invalid_identity_import_rejected','candidate_NA','completion_requires_answers','mobile_no_overflow','corrupt_storage_preserved','no_browser_script_errors','all_annotations_questionable','AI_available_across_steps','legacy_backup_new_question_blank','raw_points_without_edges','order_hypothesis_warning','oos_reason_required','oos_skip_without_fabricated_answers','oos_JSON_CSV_roundtrip','oos_changed_back_restores_requirements','suspected_oos_supported','legacy_oos_blank']},null,2));
    console.log('Questionnaire browser checks passed.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
