"""Build a no-network evidence viewer from saved results. No GT or photographs."""
from pathlib import Path
import json
R=Path(__file__).resolve().parent
D=R/'results/domains'
s=json.loads((D/'domains_summary.json').read_text())
inputs={p.stem:json.loads(p.read_text()) for p in (R/'inputs').glob('*-*.json')}
obj={'states':s,'nodes':json.loads((D/'node_lookup.json').read_text()),'baselines':json.loads((D/'baseline_partitions.json').read_text()),
 'domains':{x['domain_id']:json.loads((D/(x['domain_id']+'.json')).read_text()) for x in s if x.get('domain_id')},
 'unb':json.loads((R/'results/diagnostics/unb_target_layers.json').read_text()),'inputs':inputs,
 'human':json.loads((R/'inputs/human_review.json').read_text())}
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>局部对应与上下目标分离</title>
<style>body{font:15px/1.65 system-ui,"Noto Sans CJK SC",sans-serif;color:#17212c;background:#f5f7fa;margin:0}main{max-width:1280px;margin:auto;padding:28px}h1{font-size:27px}h2{font-size:21px}h3{font-size:17px}section{background:white;padding:22px;border:1px solid #dce2e8;border-radius:8px;margin:18px 0}select{font:inherit;padding:5px;margin:5px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid #dce2e8;padding:7px;vertical-align:top}th{background:#eef2f5}.note{color:#495968}.warning{border-left:4px solid #b66f1c;padding:8px 14px;background:#fff9ef}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.plot{width:100%;height:auto;border:1px solid #e4e9ee}code{font-size:13px}.moved{background:#fff2d9}.tag{background:#edf2fa;padding:3px 9px;border-radius:4px}details{margin-top:12px}.s0{fill:#1264a3}.s1{fill:#cb6d1f}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style>
<main><h1>局部替代对应与上下目标分离</h1><p>固定main：4716aef3… · 66份作答 / 24名人员 / 400个原角对 · <b>无GT、无原图、没有构造新环</b></p>
<p class="warning">此页展示局部旧分区、自动/人工辅助数值结果及E/W前沿，不逐条加载百万候选。完整可行集合在gzip账本；可用extract_candidate.py恢复任一完整分区。5°仅演示，所有门限未经校准。</p>
<section><h2>一、局部重分配与完整人员池</h2><label>图片 <select id="image"></select></label><label>距离 <select id="metric"><option value="pair">绑定上下</option><option value="bottom">下端</option><option value="top">上端</option></select></label><label>阈值 <select id="tau"></select></label><label>局部域 <select id="domain"></select></label><label>候选 <select id="candidate"></select></label>
<div id="status"></div><div class="grid"><div><h3>上端原观察与条件中位位置</h3><svg id="top" viewBox="0 0 580 350" class="plot"></svg></div><div><h3>下端原观察与条件中位位置</h3><svg id="bottom" viewBox="0 0 580 350" class="plot"></svg></div></div>
<p class="note">圆点为原观察，十字为给定分组的中位位置。橙/蓝只区分组，不代表好坏。重合圆点仍分别存在；悬停可读来源，完整来源见下表。纵轴沿ERP向下，不连接新环。</p>
<div id="members"></div><details><summary>该图完整当前人员名单（不只显示局部人员）</summary><div id="roster"></div></details></section>
<section><h2>二、unb：底部身份、原始配对与上端目标</h2><label>同一探索阈值 <select id="unbtau"></select></label><div id="unb"></div></section>
<section><h2>证据界限</h2><p>人工辅助结果明确使用开发判断。自动策略只收到窗口定位种子，不收到人审关系；窗口定位本身不是盲目检测。组内离散度降低不等于身份改善；最小修改不等于不损害其他成员。局部域外成员与全部源环固定。</p><p>完整布局有效性、两对/三对局部结构等价和上端任务政策尚未解决。相同底部组、上端几何组和语义目标是三个不同对象。</p><p><a href="REPORT_ZH.html">研究报告</a> · <a href="results/summary/selected_movement_summary.csv">成员变化CSV</a> · <a href="results/diagnostics/rpc_all_assisted_alternatives_summary.json">全部人审相容成员范围</a></p></section></main>
<script id="dataset" type="application/json">DATA</script><script>
'use strict';const data=JSON.parse(document.getElementById('dataset').textContent),$=x=>document.getElementById(x),e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(x,n=6)=>x==null?'—':Number(x).toFixed(n);
function opt(id,arr,val){$(id).innerHTML=arr.map(a=>`<option value="${e(a[0])}">${e(a[1])}</option>`).join('');if(val!=null)$(id).value=val}
opt('image',Object.keys(data.inputs).map(x=>[x,x]),'rPc6DW4iMge-06');for(let id of ['tau','unbtau'])opt(id,[1,2.5,5,7.5,10].map(x=>[x,x+'°（未校准）']),5);
function refill(){let ss=data.states.filter(s=>s.image==$('image').value&&s.metric==$('metric').value&&s.threshold==+$('tau').value&&s.domain_id);opt('domain',ss.map(s=>[s.domain_id,s.domain_id.split('_').slice(-1)[0]+': '+s.baseline_sizes.join('+')+'人次/角对']));refillCandidate()}
function refillCandidate(){let d=data.domains[$('domain').value];if(!d){opt('candidate',[]);draw();return}opt('candidate',d.selected_details.map(c=>{let labels=[];if(c.edit_count==0)labels.push('旧分区');if(d.automatic.selected_ids.includes(c.local_id))labels.push('自动');if(d.human_assisted?.selected_ids.includes(c.local_id))labels.push('人工辅助');if(d.pareto_ids.includes(c.local_id))labels.push('E/W前沿');return[c.local_id,labels.join(' / ')+'：#'+c.local_id+'，移动'+c.edit_count]}));let best=d.human_assisted?.selected_ids[0];if(best!=null)$('candidate').value=best;draw()}
function plot(id,ns,blocks,centers,side){let pts=blocks.flat().map(i=>ns[i].points[side]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);let lo=Math.min(...xs),hi=Math.max(...xs),ly=Math.min(...ys),hy=Math.max(...ys),dx=Math.max(hi-lo,2),dy=Math.max(hy-ly,2);lo-=dx*.1;hi+=dx*.1;ly-=dy*.15;hy+=dy*.15;let X=x=>55+(x-lo)/(hi-lo)*495,Y=y=>25+(y-ly)/(hy-ly)*285;
let s='';for(let k=0;k<=4;k++){let x=lo+(hi-lo)*k/4,y=ly+(hy-ly)*k/4;s+=`<line x1="${X(x)}" y1="25" x2="${X(x)}" y2="310" stroke="#e2e7ed"/><text x="${X(x)}" y="330" text-anchor="middle" font-size="11">${num(x,1)}</text><line x1="55" y1="${Y(y)}" x2="550" y2="${Y(y)}" stroke="#e2e7ed"/><text x="49" y="${Y(y)+4}" text-anchor="end" font-size="11">${num(y,1)}</text>`}
blocks.forEach((g,gi)=>g.forEach(i=>{let n=ns[i],p=n.points[side];s+=`<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="5" class="s${gi}" opacity=".75"><title>${e(n.id)} / ${e(n.worker)} / 处理后${n.pair_index} / 源${n.source_pair_index} (${num(p[0])}, ${num(p[1])})</title></circle>`}));(centers||[]).forEach((c,i)=>{if(!c.points)return;let p=c.points[side],x=X(p[0]),y=Y(p[1]);s+=`<path d="M${x-8},${y}H${x+8} M${x},${y-8}V${y+8}" fill="none" stroke="${i?'#cb6d1f':'#1264a3'}" stroke-width="2.5"><title>条件中位位置 ${num(p[0])}, ${num(p[1])}</title></path>`});$(id).innerHTML=s}
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th>'+e(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function draw(){let code=$('image').value,d=data.domains[$('domain').value],ns=data.nodes[code],base=data.baselines.find(x=>x.image==code&&x.metric==$('metric').value&&x.threshold==+$('tau').value);$('roster').innerHTML=table(['记录','人员','原角对数','原环'],data.inputs[code].records.map(r=>[e(r.id),e(r.worker),r.points.length/2,e(r.order_status)]));if(!d){$('status').innerHTML='<p>此状态没有阈值内跨组局部域；基线保留。所有原观察仍在完整分区中。</p>';$('top').innerHTML='';$('bottom').innerHTML='';$('members').innerHTML='';return}
let c=d.selected_details.find(x=>x.local_id==+$('candidate').value),bp=c.human_development_probe||{},old={};d.domain.baseline_blocks.forEach((g,i)=>g.forEach(n=>old[n]=i));let label=c.block_label_alignments[0],moved=new Set(c.moved_nodes_alternative_alignments.flat());
$('status').innerHTML=`<p><span class="tag">全池 ${base.roster_denominator} 人 / ${ns.length} 原角对</span> 局部 ${d.domain.union_nodes} 观察，${d.domain.feasible_count} 个合法二组分区。域外固定。</p><p>W=${num(c.cost,9)}；移动数=${c.edit_count}；新组 ${c.supports.join('/')}；拆开旧关系 ${c.lost_coassignments.length}，新增关系 ${c.added_coassignments.length}；拆开同坐标关系 ${c.newly_split_identical_coordinates.length}。指定正确三点同组：${e(bp.same_group??'无身份人审')}；旧误选三点同组：${e(bp.wrong_triple_same_group??'不适用')}。</p><p class="note">自动状态：${e(d.automatic.status)}；人工辅助状态：${e(d.human_assisted?.status??'未设置')}。本地整数索引仅用于证据定位。没有新环，不能移用旧完整布局IoU。</p>`;
plot('top',ns,c.blocks,c.centers,0);plot('bottom',ns,c.blocks,c.centers,1);
$('members').innerHTML=table(['记录 / worker','处理后 → 源角对','原组 → 候选组','上端 (x,y)','下端 (x,y)','来源/状态'],c.blocks.flatMap((g,gi)=>g.map(i=>{let n=ns[i];return[e(n.id)+' / '+e(n.worker),n.pair_index+' → '+n.source_pair_index,old[i]+' → '+(gi^label)+(moved.has(i)?' <b>移动</b>':''),e(n.points[0].map(x=>num(x,3)).join(', ')),e(n.points[1].map(x=>num(x,3)).join(', ')),e(n.source_order_status)]}))) }
function drawUnb(){let a=data.unb.find(x=>x.threshold_deg==+$('unbtau').value);let names={low_glass_top:'已审：矮玻璃顶部',glass_to_ceiling:'已审：延伸到天花板',unknown:'上端语义未知（不是一个目标）'};$('unb').innerHTML=`<p>全池15人；A所在底部几何组${a.bottom_support}人。已审下端关系仅三点且为审慎判断；其他成员不能据此认证。</p>`+table(['上端记录类别','来源数','原点对关联数','底部边际支持','来源','条件上端位置'],a.targets.map(t=>[e(names[t.target]),t.top_support,t.original_pair_incidence,t.bottom_marginal_support,e(t.members.map(x=>x.join(':')).join(', ')),t.center_of_own_sources?.points?e(t.center_of_own_sources.points[0].map(x=>num(x,3)).join(', ')):'不合并未知目标']))+`<p class="note">原点对关联不是对新生成坐标的联合票。未选择任务上端，没有将条件上/下中位x强制对齐。</p>`+table(['上端几何组','几何人数','源观察','其中未知来源数'],a.geometric_top_subgroups.map((g,i)=>[i,g.geometric_support,e(g.members.map(x=>x.join(':')).join(', ')),g.unknown_members.length]))+`<p>已审观察但不在本底部组：${e(JSON.stringify(a.reviewed_members_outside_this_bottom_group))}</p>`}
for(let id of ['image','metric','tau'])$(id).addEventListener('change',refill);$('domain').addEventListener('change',refillCandidate);$('candidate').addEventListener('change',draw);$('unbtau').addEventListener('change',drawUnb);refill();drawUnb();
</script></html>'''
html=html.replace('DATA</script>',json.dumps(obj,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')+'</script>')
(R/'EVIDENCE_VIEWER_ZH.html').write_text(html,encoding='utf-8')
print('viewer',len(html))
