import json,argparse
from pathlib import Path
import numpy as np
from PIL import Image
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
parser=argparse.ArgumentParser(description='Render optional B6By upper-target review and audit existing e9z structure memberships.')
parser.add_argument('--handoff',type=Path,default=Path(__file__).resolve().parent.parent/'oct6-handoff-intake')
parser.add_argument('--out',type=Path,default=Path(__file__).resolve().parent)
parser.add_argument('--structure-file',type=Path,default=None,help='Optional e9z pair_12.json generated by the separate structure study.')
args=parser.parse_args()
ROOT=args.handoff.resolve(); OUT=args.out.resolve(); OUT.mkdir(parents=True,exist_ok=True)
D=json.loads((ROOT/'inputs.json').read_text());rs=next(im['records'] for im in D['images'] if im['image']=='B6ByNegPMKs-33')
examples=[]
fig,axs=plt.subplots(1,3,figsize=(15,9))
for ax,(rid,c) in zip(axs,[('R00345','#00eeff'),('R00274','#ffb000'),('R01988','#ff00ff')]):
 r=next(r for r in rs if r['id']==rid);p=np.array(r['points']).reshape(-1,2,2)[0]
 examples.append(dict(image='B6ByNegPMKs-33',record_id=rid,processed_pair_index=0,source_pair_index=r['source_pair_indices'][0],points=p.tolist()))
 ax.imshow(Image.open(ROOT/'images/B6ByNegPMKs-33.png'),extent=[0,1024,512,0]);ax.plot(p[:,0],p[:,1],color=c,lw=2);ax.scatter(p[:,0],p[:,1],c=c,s=35);ax.set_xlim(180,320);ax.set_ylim(340,160);ax.set_title(f'{rid}, processed p0\ntop=({p[0,0]:.1f}, {p[0,1]:.1f}), bottom y={p[1,1]:.1f}');ax.grid(alpha=.15)
fig.suptitle('NEW optional review: same upper target or different boundaries? No answer assumed.');fig.tight_layout();fig.savefig(OUT/'B6By_optional_upper_target_question.png',dpi=140)
q=dict(status='optional_new_question_not_sent_to_user',question='B6By-33: R00345 p0 and R00274 p0 refer to the same upper target with localization variation, or to distinct visible upper boundaries? R01988 p0 is a separately shown 2-person-group representative; no necessity to certify its whole group.',examples=examples,not_decided=['All other members in either group','Correct fused location','Ground truth or task target policy'])
(OUT/'optional_review_question.json').write_text(json.dumps(q,indent=2))
# Saved cross-check of another worker's already generated structure candidates.
f=args.structure_file
if f is not None and f.exists():
 s=json.loads(f.read_text());out=dict(source=str(f),scope='independent membership-level audit of generated 12-degree candidates, not new construction',policies={})
 for name,p in s['policies'].items():
  out['policies'][name]=[dict(feature_id=g['feature_id'],support=g['support'],node_indices=g['node_indices'],center=g['center']['points']) for g in p['groups'] if g['selected']]
 out['interpretation']={'three_state':'Retains rejected mixed seam location x=1.224880, loses high-y right group; four pairs is not the user-requested structure.','strict':'Removes mixed seam and retains alternate low-y 4-person right clique; splits original 8-person near-x599 identity into two 4-person groups at x598.512675 and x601.518671, producing a new close double turn. This is group-splitting evidence, not a new human label.'}
 (OUT/'e9z_structure_member_crosscheck.json').write_text(json.dumps(out,indent=2))
print(json.dumps(q,indent=2))
