from pathlib import Path
import json,gzip
R=Path(__file__).resolve().parent
D={'warning':'仅旧四图完整输入；未取得本轮新附件、e9z和五张困难图。此页不读取GT。','images':{},'states':{},'patches':[]}
for f in sorted((R/'inputs').glob('*.json')):
 if f.name=='human_review.json':continue
 im=json.loads(f.read_text());D['images'][im['image']]=im
 folder=R/'results'/im['image'];ns=json.loads((folder/'nodes.json').read_text())
 for metric in ['pair','bottom','top']:
  for tau in [5,9,12]:
   st=json.loads((folder/f'{metric}_{tau}.json').read_text());tri=json.loads((R/'results/analysis'/f'{im["image"]}_{metric}_{tau}_three_state.json').read_text())
   variants={'raw':st['raw_MV'],'strict':st['path_witness_MV'],'three':tri}
   hf=R/'results/analysis'/f'{im["image"]}_{metric}_{tau}_human_assisted.json'
   if hf.exists():
    z=json.loads(hf.read_text())
    if 'reports' in z:variants['human']=dict(z,groups=z['reports'])
   D['states'][f'{im["image"]}|{metric}|{tau}']={'variants':variants,'nodes':ns,'changes':st['changes'],'evidence':st['path_evidence_summary']}
for f in sorted((R/'results/patches').glob('*_candidate_rings.jsonl.gz')):
 D['patches'].extend(json.loads(line) for line in gzip.open(f,'rt'))
payload=json.dumps(D,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
html=r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>连续短路径｜来源与候选</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f4;color:#23303a;font:15px/1.6 system-ui,"Noto Sans CJK SC",sans-serif}header{padding:22px 28px;background:#183f47;color:#fff}header h1{margin:0 0 8px;font-size:23px}.limit{font-size:13px;color:#ddebed}main{max-width:1550px;margin:auto;padding:18px 22px}.bar{display:flex;gap:12px;flex-wrap:wrap;padding:14px;background:#fff;border:1px solid #cdd6d6}label{display:flex;gap:6px;align-items:center}select,button,input{font:inherit;max-width:550px}select,button{padding:5px;border:1px solid #adbabd;background:#fff}button{cursor:pointer}.state{padding:12px 15px;border-left:4px solid #857743;background:#fcf8e8;margin:14px 0}.layout{display:grid;grid-template-columns:minmax(600px,2.5fr) minmax(290px,1fr);gap:16px}.panel{background:#fff;padding:12px;border:1px solid #d4dcdc;margin-bottom:14px}h2{margin:0 0 8px;font-size:17px}canvas{width:100%;height:auto;display:block;background:#fafbfa}.legend{font-size:13px;margin-bottom:5px}.inspector{font-size:12px;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere;max-height:1050px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid #dde3e2;padding:5px}#patchbar{margin-top:8px}a{color:#1e6176}.note{font-size:13px}#geom{font-family:ui-monospace,monospace}@media(max-width:1050px){.layout{grid-template-columns:1fr}main{padding:12px}header{padding:18px}}.pill{display:inline-block;padding:2px 8px;background:#e6edef;border-radius:4px;margin-right:7px}</style></head><body>
<header><h1>连续短路径：原MV、结构对照和条件候选</h1><div class="limit">旧四图机制实验。新附件未取得；不包含本轮e9z／五张困难图。不读GT，不根据参考挑候选，不作视觉裁决。</div></header><main>
<div class="bar"><label>图片 <select id="image"></select></label><label>门限 <select id="tau"><option>5</option><option>9</option><option>12</option></select>°（未校准）</label><label>模式 <select id="mode"><option value="mv">身份／实际达票点</option><option value="patch">两对／三对条件候选</option></select></label><label id="metlabel">身份距离 <select id="metric"><option value="pair">绑定上下</option><option value="bottom">下端</option><option value="top">上端</option></select></label><label id="polabel">政策 <select id="policy"><option value="raw">原距离MV</option><option value="strict">严格短路径门</option><option value="three">三状态对照（开发后加）</option><option value="human">人工焦点关系（单独）</option></select></label></div>
<div id="patchbar" class="bar"><label>候选 <select id="candidate"></select></label><button id="prev">上一项</button><button id="next">下一项</button><button id="export">导出此项JSON</button></div>
<div class="bar" style="margin-top:8px"><label><input type="checkbox" id="showsource">显示全部原观察（只读）</label><label><input type="checkbox" id="xring">显示中心x诊断闭环（不继承源环）</label><label>本地叠加图 <input type="file" id="background" accept="image/*"></label><button id="clearbg">清除图像</button><span class="note">图像仅在当前浏览器使用，不上传。1024×512连续标注坐标。</span></div>
<div class="state" id="status"></div>
<div class="layout"><section><div class="panel"><h2>上下点与中心投影曲线</h2><div class="legend" id="legend"></div><canvas id="erp" width="1024" height="512"></canvas><p class="note">点击MV中心点可查看所有供者。上下曲线显示用密采样；数值判断来自保存的连续路径算法，不从本画布采样。</p></div><div class="panel"><h2>声明BEV与候选范围（h）</h2><canvas id="bev" width="1024" height="510"></canvas><p class="note">能组成多边形不等于物理或语义正确；不足三对时只显示点，不补足。</p></div><div class="panel"><h2>当前名单</h2><div id="roster"></div></div></section><aside><div class="panel"><h2>支持、来源与不确定性</h2><pre class="inspector" id="inspect"></pre></div></aside></div>
<div class="panel"><h2>审查提示</h2><p>路径供者、外锚点身份组、局部相容、融合坐标和完整候选是不同对象。局部匹配有来源不等于候选整体获得相同人数支持。未知语义不因同组而传播。原始MV、严格门失败和后中心化失败均保留。</p><p>此页保留新环诊断，但没有默认按x重排任何复杂确认源环。源路径方向与处理后／源点号在导出JSON中分别保存。仅做本地叠加审核，不代替正式源审核。</p></div>
<script id="data" type="application/json">__DATA__</script><script>
const D=JSON.parse(document.getElementById('data').textContent),$=x=>document.getElementById(x);let bg=null,shown=[],active=null,hitpoints=[];
const names={raw:'原距离MV',strict:'严格短路径门',three:'三状态对照',human:'人工焦点关系辅助'};
for(const k of Object.keys(D.images)) $('image').add(new Option(k,k));$('image').value='rPc6DW4iMge-06';
function rv(p){let u=2*Math.PI*(p[0]/1024-.5),v=Math.PI*(.5-p[1]/512);return [Math.cos(v)*Math.sin(u),Math.sin(v),-Math.cos(v)*Math.cos(u)]}
function proj(v){let n=Math.hypot(...v);return [((Math.atan2(v[0],-v[2])/(2*Math.PI)+.5)%1+1)%1*1024,(.5-Math.asin(Math.max(-1,Math.min(1,v[1]/n)))/Math.PI)*512]}
function pairPoints(p){let q=[];for(let i=0;i<p.length;i+=2)q.push([p[i],p[i+1]]);return q}
function arc(a,b){a=rv(a);b=rv(b);let dp=Math.max(-1,Math.min(1,a.reduce((s,v,i)=>s+v*b[i],0))),th=Math.acos(dp);if(th>Math.PI-1e-8)return [];let N=Math.max(2,Math.ceil(th*180/Math.PI));let out=[];for(let i=0;i<=N;i++){let t=i/N,v=th<1e-10?a:a.map((v,k)=>(Math.sin((1-t)*th)*v+Math.sin(t*th)*b[k])/Math.sin(th));out.push(proj(v))}return out}
function lineE(ctx,p,color,width=1,dash=[]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();for(let i=0;i<p.length;i++){if(i===0||Math.abs(p[i][0]-p[i-1][0])>512)ctx.moveTo(...p[i]);else ctx.lineTo(...p[i])}ctx.stroke();ctx.setLineDash([])}
function drawRingE(ctx,ps,color,w=1,closed=true,nodes=false,dash=[]){if(!ps||!ps.length)return;let q=pairPoints(ps);for(let j=0;j<2;j++)for(let i=0;i<(closed?q.length:q.length-1);i++)lineE(ctx,arc(q[i][j],q[(i+1)%q.length][j]),color,w,dash);if(nodes){ctx.fillStyle=color;for(let i=0;i<q.length;i++){for(let s=0;s<2;s++){ctx.beginPath();ctx.arc(q[i][s][0],q[i][s][1],3,0,Math.PI*2);ctx.fill()}ctx.font='10px sans-serif';ctx.fillText(i,q[i][0][0]+4,q[i][0][1]-5)}}}
function floor(ps){if(!ps||!ps.length)return [];return pairPoints(ps).map(q=>{let v=rv(q[1]);return v[1]<-1e-10?[-v[0]/v[1],-v[2]/v[1]]:null}).filter(Boolean)}
function pretty(z){$('inspect').textContent=JSON.stringify(z,null,2)}
function getState(){return D.states[$('image').value+'|'+$('metric').value+'|'+$('tau').value]}
function fillCandidates(){shown=D.patches.filter(c=>c.image===$('image').value&&c.threshold_deg===+$('tau').value);$('candidate').innerHTML='';for(let i=0;i<shown.length;i++){let c=shown[i];$('candidate').add(new Option(`${i+1}/${shown.length} ${c.base_record} [${c.base_processed_path}] ← ${c.donor_record} [${c.donor_path_used_order}] · ${c.post_center_compatibility_status}`,String(i)))}render()}
function render(){let patch=$('mode').value==='patch';$('patchbar').style.display=patch?'flex':'none';$('metlabel').style.display=patch?'none':'flex';$('polabel').style.display=patch?'none':'flex';let im=D.images[$('image').value],state=getState(),v=state.variants[$('policy').value];let ec=$('erp').getContext('2d'),bc=$('bev').getContext('2d');ec.clearRect(0,0,1024,512);bc.clearRect(0,0,1024,510);if(bg){ec.globalAlpha=.8;ec.drawImage(bg,0,0,1024,512);ec.globalAlpha=1}ec.strokeStyle='#d7dedd';ec.lineWidth=.6;for(let x=0;x<=1024;x+=128){ec.beginPath();ec.moveTo(x,0);ec.lineTo(x,512);ec.stroke();ec.fillStyle='#617074';ec.fillText(x,x+2,508)}for(let y=0;y<=512;y+=128){ec.beginPath();ec.moveTo(0,y);ec.lineTo(1024,y);ec.stroke();ec.fillStyle='#617074';ec.fillText(y,2,y+12)}
$('roster').innerHTML='<table><tr><th>作答</th><th>人员</th><th>原点对数</th><th>源环状态</th></tr>'+im.records.map(r=>`<tr><td>${r.id}</td><td>${r.worker}</td><td>${r.points.length/2}</td><td>${r.order_used||r.order_status}</td></tr>`).join('')+'</table>';
let geo=[];hitpoints=[];
if($('showsource').checked){ec.globalAlpha=.28;for(let r of im.records)drawRingE(ec,r.points,'#6d7578',.65,true,false);ec.globalAlpha=1;geo.push(...im.records.map(r=>({points:r.points,c:'#d0d7d8',w:1})));}
if(patch){let c=shown[+$('candidate').value];active=c;if(!c){$('status').textContent='该图/门限没有两对／三对替换候选。不是补点失败，不构造虚假候选。';pretty({status:'no_2_vs_3_patch_candidates',full_roster:im.records.map(r=>r.id)});$('legend').textContent='无候选';drawBEV(geo);return}
let base=im.records.find(r=>r.id===c.base_record),donor=im.records.find(r=>r.id===c.donor_record);drawRingE(ec,base.points,'#777d82',1.3,true,false);drawRingE(ec,c.anchor_only_control_points,'#c18a28',1.6,true,false,[5,4]);drawRingE(ec,c.points,'#17637e',2,true,true);let dq=pairPoints(donor.points),loc=c.donor_path_used_order.flatMap(i=>dq[i]);drawRingE(ec,loc,'#8c4380',2.3,false,true);
geo.push({points:base.points,c:'#777d82',w:1.5},{points:c.anchor_only_control_points,c:'#c18a28',w:2,d:[5,4]},{points:c.points,c:'#17637e',w:2.5});
$('status').textContent=`${c.status}；${c.post_center_compatibility_status}。全池仍${c.vote_denominator_unchanged}人，但这是“单份外部环境＋另一条原路径”的条件候选，不是全员共识；整体支持未建立。`;
$('legend').innerHTML='<span style="color:#777d82">灰：原base</span>　<span style="color:#c18a28">黄虚线：仅移动锚点</span>　<span style="color:#17637e">蓝：新候选</span>　<span style="color:#8c4380">紫：原donor局部路径</span>';pretty(c);
}else{active=v;if(!v){$('status').textContent='此图未提供人工焦点辅助结果。';pretty({status:'no_human_constraints_here'});$('legend').textContent='未生成';drawBEV(geo);return}
let g=v.groups.filter(g=>g.selected);let ps=g.flatMap(g=>g.center.points||[]);for(let gr of g){let p=gr.center.points;if(!p)continue;ec.fillStyle='#17637e';ec.strokeStyle='#17637e';ec.lineWidth=.9;ec.beginPath();ec.moveTo(...p[0]);ec.lineTo(...p[1]);ec.stroke();for(let q of p){ec.beginPath();ec.arc(...q,4,0,2*Math.PI);ec.fill();hitpoints.push({p:q,g:gr})}ec.font='12px sans-serif';ec.fillText(gr.feature_id+' '+gr.support+'/'+im.records.length,p[0][0]+5,p[0][1]-6)}
let x=v.ring&&v.ring.x_diagnostic;if($('xring').checked&&x&&x.points){drawRingE(ec,x.points,'#c18a28',1.6,true,false,[5,3]);geo.push({points:x.points,c:'#c18a28',w:2})}else geo.push({points:ps,c:'#17637e',w:0});
$('status').textContent=`${names[$('policy').value]}：${g.length}组实际达票身份／完整池${im.records.length}人。不强制四对。完整源身份环可用：${v.ring&&v.ring.primary_ring_available?'是（仍需解释）':'否，保留点与路径层'}。${$('policy').value==='human'?'本项使用旧开发人工关系，不能当自动成功。':''}`;
$('legend').textContent='蓝：实际达票身份与支持；点击点查看完整成员。黄色虚线仅在手动打开x诊断时显示。';pretty({image:im.image,policy:names[$('policy').value],threshold_deg:+$('tau').value,full_pool:im.records.length,actual_selected_groups:g.length,minimum_four_pairs:false,group_supports:g.map(z=>({id:z.feature_id,support:z.support})),evidence:state.evidence,changes:v.changes||($('policy').value==='strict'?state.changes:undefined),note:'未审成员关系变化不自动是纠错或损害；原始源环未排序改写。'});
}drawBEV(geo)}
function drawBEV(geo){let ctx=$('bev').getContext('2d');let all=geo.flatMap(g=>floor(g.points));if(!all.length)return;let xs=all.map(p=>p[0]),zs=all.map(p=>p[1]),x0=Math.min(-.1,...xs),x1=Math.max(.1,...xs),z0=Math.min(-.1,...zs),z1=Math.max(.1,...zs),s=Math.min(934/(x1-x0),420/(z1-z0)),cx=(x0+x1)/2,cz=(z0+z1)/2;function f(p){return [512+(p[0]-cx)*s,255-(p[1]-cz)*s]}ctx.strokeStyle='#cdd7d8';let o=f([0,0]);ctx.beginPath();ctx.moveTo(o[0]-8,o[1]);ctx.lineTo(o[0]+8,o[1]);ctx.moveTo(o[0],o[1]-8);ctx.lineTo(o[0],o[1]+8);ctx.stroke();ctx.fillStyle='#56646a';ctx.fillText('camera',o[0]+10,o[1]);for(let g of geo){let p=floor(g.points).map(f);ctx.strokeStyle=g.c;ctx.fillStyle=g.c;ctx.lineWidth=g.w||1;ctx.setLineDash(g.d||[]);if(g.w&&p.length>=3){ctx.beginPath();p.forEach((x,i)=>i?ctx.lineTo(...x):ctx.moveTo(...x));ctx.closePath();ctx.stroke()}for(let x of p){ctx.beginPath();ctx.arc(...x,3,0,Math.PI*2);ctx.fill()}ctx.setLineDash([])}}
$('erp').addEventListener('click',e=>{if($('mode').value!=='mv')return;let box=$('erp').getBoundingClientRect(),x=(e.clientX-box.left)/box.width*1024,y=(e.clientY-box.top)/box.height*512;let near=hitpoints.map(p=>({d:Math.hypot(p.p[0]-x,p.p[1]-y),g:p.g})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<18){let ns=getState().nodes;pretty({...near.g,members:near.g.node_indices.map(i=>ns[i]),interpretation:'底部或顶部组的票不能无条件复制给另一端语义。中心是条件估计。'})}});
for(let id of ['image','tau'])$(id).onchange=fillCandidates;for(let id of ['mode','metric','policy','showsource','xring','candidate'])$(id).onchange=render;$('prev').onclick=()=>{if(shown.length){$('candidate').selectedIndex=($('candidate').selectedIndex-1+shown.length)%shown.length;render()}};$('next').onclick=()=>{if(shown.length){$('candidate').selectedIndex=($('candidate').selectedIndex+1)%shown.length;render()}};$('export').onclick=()=>{if(!active)return;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(active,null,2)],{type:'application/json'}));a.download=(active.id||'current_state')+'.json';a.click();URL.revokeObjectURL(a.href)};$('background').onchange=e=>{let f=e.target.files[0];if(!f)return;let img=new Image();img.onload=()=>{bg=img;render()};img.src=URL.createObjectURL(f)};$('clearbg').onclick=()=>{bg=null;$('background').value='';render()};fillCandidates();
</script></main></body></html>'''
(R/'EVIDENCE_VIEWER_ZH.html').write_text(html.replace('__DATA__',payload),encoding='utf-8')
print('viewer bytes', (R/'EVIDENCE_VIEWER_ZH.html').stat().st_size,'patches',len(D['patches']))
