"""Compare a clean recomputation with the packaged canonical results."""
from pathlib import Path
import argparse,csv,json,math

ROOT=Path(__file__).resolve().parent
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('output',help='Directory generated by check_panel.py')
parser.add_argument('--reference',default=str(ROOT/'results'),help='Canonical result directory')
args=parser.parse_args()
actual=Path(args.output);reference=Path(args.reference)
maximum=0.;numbers=0

def compare(x,y,path):
    global maximum,numbers
    if isinstance(x,dict):
        assert isinstance(y,dict) and x.keys()==y.keys(),path
        for key in x:compare(x[key],y[key],path+'/'+key)
    elif isinstance(x,list):
        assert isinstance(y,list) and len(x)==len(y),path
        for i,(xx,yy) in enumerate(zip(x,y)):compare(xx,yy,path+'/'+str(i))
    elif isinstance(x,bool) or x is None:
        assert x==y,path
    else:
        try:a=float(x);b=float(y)
        except (ValueError,TypeError):
            assert x==y,(path,x,y)
        else:
            assert math.isfinite(a) and math.isfinite(b),path
            difference=abs(a-b);maximum=max(maximum,difference);numbers+=1
            assert difference<=1e-12,(path,a,b,difference)

files=['same_k_shape.csv','raw_dispersion.csv','roster.csv','input_audit.csv',
       'excluded_records.csv','two_image_equivalence.csv','comparison_by_image.csv',
       'summary.json','DESIGN.json']
for name in files:
    a=actual/name;b=reference/name
    if name.endswith('.csv'):
        with a.open() as f:av=list(csv.DictReader(f))
        with b.open() as f:bv=list(csv.DictReader(f))
    else:av=json.loads(a.read_text());bv=json.loads(b.read_text())
    compare(av,bv,name)
print(json.dumps({'status':'passed','result_files_compared':len(files),'numeric_values_compared':numbers,
                  'maximum_absolute_numeric_difference':maximum,'absolute_tolerance':1e-12,
                  'non_numeric_fields':'exact_match'},indent=2))
