"""Private report from frozen selection; blank/undefined coverage remains undefined."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def read(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def fmt(n):return '未定义/缺' if n is None else f'{n:.6f}'
def main():
 d=read(ROOT/'results/selection_private.json');cv=read(ROOT/'results/boundary_coverage_private.json');refs={r['selection_private']['record_id']:r['case_id'] for r in d['records']}
 lines=['# 30份唯一作答：冻结候选清单与覆盖/缺口（主审私有）','','状态：**候选版v1先交主审；最终用户页、叠线和回执尚未生成。旧8例及回执未改。**','',f"已合入实际main `{d['main_checked_and_merged']}`；正式输入 `{d['formal_input_commit']}`。只新增独立研究工件，不改原数据、GT、资格、旧分数，不推main。",'','30个不同record_id及object_id：24质量+6空间。24张原照片；质量12个既有room_group。质量池1059减冻结留出交集152=907记录/83图；完整282留出保持排除。空间资格池272记录/21图。','','## 工件','','- `selection_private.csv/json`：30行可审核清单、资格/参考/来源、五原公式与所有边界距离、曝光及照片哈希；禁止放入用户包。','- `boundary_coverage_private.json`：声明控制池、全池最近邻与所选距离分开。','- `selected_original_photos_private.zip`：24张原字节照片；`pixel_sheet_1..4.jpg`仅供主审查看原像素，尚不是最终叠线。','- `selected_geometry_private.json`：30作答、原参考及6份B底面；所有新B缺top，不造完整B Q。','- `pixel_audit_private.json`：真实照片观察及复杂顶面/门洞/遮挡的适用性疑点；需主审终审，未预填质量判断。','','## 唯一记录清单','','以下分层只是数值选样依据，不能称为人工质量等级、成因或空间意图。空间行Q只是原参考下既有诊断，不用于空间归属。','','|题号|record_id|object_id|图像|v1.1 Q|D°|F°|采样依据|','|---|---|---|---|---:|---:|---:|---|']
 for r in d['records']:
  c=r['components'];lines.append(f"|{r['case_id']}|{r['selection_private']['record_id']}|{r['object_id']}|{r['image_code']}|{r['frozen_formulas']['Q_v11']:.5f}|{c['dir']:.5f}|{c['flat']:.5f}|{'; '.join(r['selection_private']['selection_labels'])}|")
 lines+=['','T30保留既有`scope_and_order_difference_not_global_error`说明，restrict_primary=false；不把它虚报为错误GT，也不隐藏限制。','','## 边界覆盖','','Q全池近邻；D/F优先 I≥.6、S≤6°、Hstar≤.4，另方向F≤3°、平整D≤5°。S使用冻结`boundary_rms_deg`。半损失尺度D5°/F2°不是合格线。控制最近与全池最近在JSON分开保存。','','|量|界点|侧|控制池最近|距离|实际所选最近|距离|所选满足控制|','|---|---:|---|---|---:|---|---:|---|']
 for r in cv:lines.append(f"|{r['metric']}|{r['level']}|{r['side']}|{r['nearest_record_id'] or '缺'}|{fmt(r['absolute_distance'])}|{refs.get(r['selected_nearest_record_id'],'缺')} / {r['selected_nearest_record_id'] or '缺'}|{fmt(r['selected_distance'])}|{r['selected_nearest_satisfies_control']}|")
 lines+=['','- v1.1 Q95/85/50两侧全部是907池真正最近邻：95下/上距0.088251/0.073545，85下/上0.035287/0.019094，50下/上0.044011/0.105338。','- D5/10/15两侧与20下侧是声明控制子集最近。D15下距0.471391、上距0.555663；20下距0.576184。全907的D最大19.423816，没有20上侧。','- F2/4两侧与6下有受控例。F4下3.494450（差0.505550），6下5.688942（差0.311058）。','- 受控池无F6上侧；T19为全907唯一F>6例：F7.640835、D18.533474，距6为1.640835。只作联合混杂诊断，不能称紧邻、纯平整证据。全907无F8上侧；8下7.640835同样混杂。','- 补充Q75下侧T24是全池最近邻；Q90两侧、75上侧、60两侧没有紧邻覆盖，具体距离见表。没有拿留出/错误例补洞；主审可明确替换辅助槽位，另存v2并保留v1。','- T20高Hstar同时高S，T21低I只作位置/范围代理，T22按Hlocal−Hmean取局部结构代理；不能解释为已分离的单误差因果。','','## 独立成对题与空间证据','','可选P01引用T23/T24，同图同参考；不增加唯一作答数，不强迫跨图排名。v1.1 Q(T24−T23)=+1.496052，alpha30差=-0.003226，是很小的原候选排序反转。主审最终表示/采样核验后决定是否保留成对题。单份绝对评价先填，成对答案独立。','','|题号|A边界RMS/h|B边界RMS/h|B−A|A角点Fréchet/h|B角点Fréchet/h|A区别区覆盖|B区别区覆盖|','|---|---:|---:|---:|---:|---:|---:|---:|']
 for r in d['records'][24:]:
  m=r['space_geometry_metrics'];lines.append('|'+r['case_id']+'|'+ '|'.join(fmt(m.get(k)) for k in ['A_boundary_rms_h','B_boundary_rms_h','boundary_rms_h_B_minus_A','A_corner_frechet_h','B_corner_frechet_h','exclusive_A_coverage','exclusive_B_coverage'])+'|')
 lines+=['','区别区为空时覆盖未定义，不能填0伪装测量。空间采样.25h仅是敏感性分层，不是最终阈值；保留绝对不匹配、相对差距、IoU、外部面积。T28边界与角点偏好冲突；T29两区别区均相交但尺度不对称（A7.615270h²、B.031651h²），只称几何混合候选，不认定斜跨真实意图。T29/T30两参考绝对距离都大；“语义上确实斜跨”仍待用户判断/可能需替换，不宣称已充分覆盖。','','## 曝光、判题、停止点','','全部为历史数据，不声明历史未见。T17复用旧C07记录，T23/T24复用旧C04记录；T01、T09、T22等同图曝光单独记载。C02/C05不进入本保守池，旧样本保持一般观察用途、不得纯惩罚拟合。','','未来用户页隐藏Q、方案/参数、人员和选样理由。空间选项严格使用：仅 A 可匹配 / 仅 B 可匹配 / 两者均可匹配 / 两者均不匹配 / 无法判断。所有回答默认空。新回执需独立版本/键/30ID，旧8版本应拒绝而不清当前回答；分页进度不得把查看/空白当作接受。','','**本阶段先交清单，无用户ZIP，无最终渲染或用户答案。** 主审决定适用性、替换和小样后继续最后渲染、30份回执与浏览器测试。','','主审已有12份Q近邻的六环表示/2048与4096采样检查，最大Q极差0.00014842684333871148，未跨六测试界点。本阶段不重复、不冒称云端复跑，不将它作为人类有效性证据或最终选例替代。','','阈值导向30份不能估计总体严重比例；不能同时调66组后宣布泛化成功。最终规则与main发布归主审，282留出继续排除。','','## 复现','','```bash','python code/freeze_selection.py --frozen-root /path/to/unpacked/cloud_compute --photo-root /path/to/original/assets --out /path/to/new_selection_results','```','','需要既有完整计算工件的results/inputs及旧8映射。24原图可从本目录照片ZIP取得（解压后以originals作photo-root）。冻结算法与Pro/官方IoU原件、MIT许可证仍按既有目录保留；本目录是新增选样适配，未改原件。','',f"映射SHA256：`{__import__('hashlib').sha256((ROOT/'results/selection_private.json').read_bytes()).hexdigest()}`。"]
 (ROOT/'research/COVERAGE_AND_GAPS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
if __name__=='__main__':main()
